appversion: apps/V1
kind: Deployment
metadata: 
    name: mongodb-deployment
    labels:
-   app: mongodb
    spec:
        replicas:1
        selector:
        matchlabls:
        app: mongodb
        templates:
            metadata:
                labels:
                    app: mongodb
            spec:
                containers:
                -   name: mongodb
                    image:mongodb
                    ports:
                    -   containersPort: 27017
                        env:
                        -   name: MONGO_INITDB_ROOT_USERNAME
                            value:
                        -   name: MONGO_INITDB_ROOT_PASSWORD
                            value:
                            
                        
              
            
